sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Tn5PEejAfhRAGpCrRXQs8jA55IYEPUmqjAXxPDknGT/AklK2YDFkzX7Z49G5U9donQJODk9mr8giY4jlx6nln5Z6zSWuCF3HTlZNsie8p3SUIdDg6vLL4LbTFA7zAiU2HjMFWTZYL6yUm7G11o8DmwgaFkNhC02QJciZGhrbTtC9k3aWwNmSoP9+HqbICAsDMWgy2qNnHKazUnIdtfCDKC5LdlKOnf8C2PjINJ6qBGPku56h+Im+molO0M5p3GF/dT5ySKLywxOBBOdPUQ3DBb+PsYIhJ/W58W+kQYe5Mnad3M+PGLvDmo7pV9+4gRBzWunDVvjfzFSPRT4yOzTU320tYLOmjYJT2sJafDI68FC6BMHPC7cRRlVaqZ6vZC2EdhBRan0V5HSazOHbxcehtudY999yn3OmWysvavYrc9Qwi61IgmOAc8l4I7CEMZCp0eRHdAPyZna2AS/YGvLaNHBfOyDU6IH9uHCq/+SwaSfZVK2qDeDz96OYwHBnyL8ONzPomVhMvQ09V1MP8W4yRFyx8X0350usZkdUxnPXAvZxak6U/Ltx2kV3CZ+scFl3plWDbcbJHqQRIBpvnqOEMzDYtPh7DodmTMnWCaqUA6gHQr7Dy1VkS5ESvE0L8Y8Qey3yMaXJr4qQ2xnIAFlwRDn3QmNV19HL72EV0WJ+7yU=
  - secure: MCLETlDp4S4msohcdH+uaV3MWholU1kd3FeTWks83q22PJNdRCxJw8/lxAwyV1Ki/THJDCuDFVbwdDwhwp7ST07GQjHWRuVhxF+CmKfpmvXKXcLXoHo0rbjDxAJ57THmhqT3Yi2cVQw32i8IaIKwuwHoCQ38uaCntzRO+k9YY8ZA0F5bzQbzmz3CgPCcoPlvA/8uEMgKxSXppPywzIVfS8/21sRc7bZu/APA5cg/379/1VhUoUYhdNF5nPEQkb534+ABa0j89XkwoCBrasGqYCeioMXGAWXr5S71n9kzZxr+QBUDyYxbwLQZOo9O0fxMug9uID8BZN4iYYf+27HfY27xIsQDAbIwlaJEACP8sgtuVeNqriOihkenHUmfgZEIgzpns9Iqhs/QAY5e0X8kK1gGnCJLAyPn58RXskr64wnGZec3JNE5UsZrtPcJxtPquUrFwBbJpWASbnNU1kSICkTGER9YroDqD/2yLJItEAd5xPba7VNTp9llVxhoDQTf4OICgT3D2mckYfOY0Zpy2XMPClrHf7/Fvcr9A3+KG/+6sRpTlxln8lp2A/jQkvtytMuvqUsVbwqIuYLo36ufU2JbIw00bB7XOO3qKZUE2djYspUtoPpz+jD0NY78najjJDZCXSA2gSb2Gk0j4V0ox/AqQEGL7/shsN9WMmN9/DI=
  - secure: jWm6q6z2QzdBYYEuKWazqe+Viwyn28XAmmZVrhorILDi4aNNc5fXquwhOqPlSVj+y0/gQKwARv6AA4DhcvS8uQ7TrOpdWx5Nib9c63z4gvWa/2HhjNCatMhF/R82Gd598SZgyNaaUTcQ//ksJGWQWPTZO+akQS0vzI7cdRs7r9nwevLM78HxR6ALx3B6NdtNi8gAU6llA+3Y+4kLZ9cVGHoKPH9o13Nih2vCw7ieVQZZhENUsXo0ZX2M9SAgY/PbPtItLNwBGCKMFXP43j86zx6pZMh7kYN7KeGUfnHMrdRZ2RunoESxC1uJGIpKE5mVbrXbWOD4rVuuEVL1CxteR9bMLRcJa4e6NXbVMyrpMAWSBUbgHR8QonqMUvcUWRl/QhOjLSV0ybgFWDwPDPQsg46s9Z99tH0gpnrYDa8/zUzxoIktK0AN/SIbsisZ8yMfT+1DA6ChOJLDvxroSwCIqx8+toxWtH3wUlMv09Yc5YAUdV+0c6ZPqP/ylD4xNeGDqDVsLCnTtf1FnsZwe1qWzDRXNbCNG45tkP8G6IaJ8+wpm5EMo1BehPjZA9Y2AV+ZdYbqImh/MzZ8ZdM4gGMV8v1xSQ/5jSpS4ekbf4PmujadFCK5XBGMmzEPyvvGhZ/zjmyoyKOXXC4H19a5uVIwFTipTkuqXYRctOAgrMIgL0E=
  - secure: W0KztVK6d+EuXXirIs+dtTRZzL9NWI35gDBvnCK1BTp0brIzMckgk039SVWIFG8LkkUL/cUqRv8T3ahZbmYxOSYzTJxlkaUAABNCUZAHYFbE96+z/Z8FqKjrNj6nKT5ndC+X63WFcn0kKR5bpvyp6v0o+U7AJruUoddxy1WqQi8SRP3TSrPdZ1ySERJrC5Y+ncnRC85Kqb16Ar0FDQ8CX8ufTIllCsLRQqTm5av7eG1DMo0tTgV8WYdFrrTavNs7KHfUGAIVcIp6ULXKw6u6IDMNzJOPfkqULLzAzauesU/dHEhPG+MPxvxqtwfFtSFC36NDrGS/tXQsK5Id5urrtG12Pb/aHFc4If9gHbenwBdseLxuxGG+nktFoyXUhov6PbqbEAD+1aym5JdAnT8bdhohJhBokUm/LGNryvHMlEaY4lf6x2M+z8ksM6gAFK+8cZn1+z+FwTk/T3TjannVKrgA+Zv0qKi39r5RM97qrylvxtX9HIhvyx2RMPYxL0LUPEAqxZ/lpl8rjPJKVyiFp6p3bM2X4LQr/5230/PbQxep5lguBIs7Xpcrc/lkRpiU1yu3V1nYEq+NNzZIPQHNbe3/vf6LP9RVp0eKni8toE9z3+5diTA1YIsvKZDLMBV/xcpgfNIqKbeehfk1DgYCUrWuccWA+I0TjHMSdcmt3qA=
